#!/bin/bash

program=$0
pseudo_prefix=$(cd $(dirname $program)/.. ; pwd -P)/usr

args=""
for arg in "$@" ; do
  if [ "`echo "$arg" | wc -w`" -gt "1" ] ; then
    args="$args \"$arg\""
  else
    args="$args $arg"
  fi
done

PSEUDO_PREFIX=${pseudo_prefix} ${pseudo_prefix}/bin/pseudolog -P ${pseudo_prefix} $args
